name: Random Bugs

timezone: Asia/Shanghai

permalink: /post/:title.html

disqus_shortname: randombugs

baseurl: /

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - README.markdown
  - drafts

defaults:
  -
    scope:
      path: "_posts"
      type: posts
    values:
      layout: post
