name: Random Bugs

permalink: /post/:title.html

disqus_shortname: randombugs

baseurl: /

pygments: true
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - README.markdown
  - drafts
