name: Random Bugs
description: "Whyme Lyu's blog on programming and whatnot."

domain: 5long.github.io
addr: https://5long.github.io
baseurl: /

timezone: Asia/Shanghai

permalink: /post/:title.html

disqus_shortname: randombugs


markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - README.markdown
  - drafts

defaults:
  -
    scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      og:
        type: article
        author:
          first_name: Whyme
          last_name: Lyu
          username: 5long
